project:
  type: website
  output-dir: docs

website:
  title: "Kindly Measured"
  site-url: https://yingu6.github.io/KindlyMeasured/
  favicon: logo.png
  navbar:
    title: "Kindly Measured"
    href: index.qmd
    left:
      - href: posts.qmd  
        text: Posts
      - href: about.qmd
        text: About
  open-graph: true
  # cookie-consent: 
  #   type: express
  #   style: headline
  #   palette: light

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

