project:
  type: website
  output-dir: docs

website:
  title: "Kindly Measured"
  site-url: https://yingu6.github.io/KindlyMeasured/
  favicon: logo.png
  navbar:
    logo: logo.png
    title: "Kindly Measured"
    href: index.qmd
    left:
      - href: posts.qmd  
        text: Posts
      - href: about.qmd
        text: About
  open-graph: true
  # cookie-consent: 
  #   type: express
  #   style: headline
  #   palette: light

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

# babelquarto:
#   languagecodes:
#   - name: zh
#     text: "汉"
#   - name: en
#     text: "EN"
#   mainlanguage: 'en'
#   languages: ['zh']
# title-zh: 微光成纹
# description-zh: 测试
# author-zh: Yin Gu
# lang: en

